name: .NET Build and Publish Nuget

on:
  workflow_dispatch:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish CodeCapitalWordPress
      uses: alirezanet/publish-nuget@v3.1.0
      with:
        PROJECT_FILE_PATH: src/CodeCapital.WordPress/CodeCapital.WordPress.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish CodeCapitalWordPressMvc
      uses: alirezanet/publish-nuget@v3.1.0
      with:
        PROJECT_FILE_PATH: src/CodeCapital.WordPress.Mvc/CodeCapital.WordPress.Mvc.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
